### PR TITLE
Fix box regularization

### LINKED ISSUE #116: Box regularization yields wrong orientations
## Description

Box regularization yields wrong orientations when box is not cubic or right-handed. 

## Script
Download the attached [input.txt](https://github.com/glotzerlab/garnett/files/3502115/input.txt) file, execute the script below and visualize output file.

```python
# Include a minimal script that reproduces the problem
import garnett as gt
import os
os.system("mv input.txt input.pos")
with gt.read("input.pos") as traj:
   gt.write(traj, "garnett_output.pos")
```

## Output
Output file shows wrong orientations upon visualization

## Expected output
 Identity mapping from input file to output.

## System configuration (please complete the following information):**
 - Version of Python: 3.7
 - Version of garnett: 0.4.1

## Additional context
None

### PR DESCRIPTION
**Pull request by lyrivera**
## Description

This PR fixes the box regularization when the input file contains a left-handed/not upper triangular box matrix. The format conversion if performed according to: https://lammps.sandia.gov/doc/Howto_triclinic.html

## Motivation and Context

Resolves: #116 

## How Has This Been Tested?

Old unit tests passing but no new unit tests have been added. Additionally, I have checked that the conversion yields the expected result by executing the script provided in #116.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds or improves functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update

## Checklist:

- [ ] I have read the [**CONTRIBUTING**](https://github.com/glotzerlab/garnett/blob/master/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] I have updated the documentation (if relevant).
- [ ] I have added tests that cover my changes (if relevant).
- [x] All new and existing tests passed.
- [ ] I have updated the [Changelog](https://github.com/glotzerlab/garnett/blob/master/changelog.rst).

### CODE REVIEW

**Comment by vyasr** [comment]
@lyrivera looking at the old code, I'd expect that the QR decomposition method should work, except that there may need to be a decomposition of the Q matrix into a proper rotation and a reflection where the reflection is the identity for right-handed boxes. Is that not the case? Performing the same inversion you're now doing before performing the decomposition would also be an equivalent fix.

The new method also looks fine, but it seems a little more verbose and therefore error-prone. Also, the decomposition is probably more stable than performing all of these operations in case you have super sheared boxes or other cases where loss of orthogonality is a possibility when you do the manual operations you have like the computation of square roots.

Just my two cents, feel free to proceed if you think the new code is better.

**Comment by lyrivera** [comment]
> @lyrivera looking at the old code, I'd expect that the QR decomposition method should work, except that there may need to be a decomposition of the Q matrix into a proper rotation and a reflection where the reflection is the identity for right-handed boxes. Is that not the case? Performing the same inversion you're now doing before performing the decomposition would also be an equivalent fix.

I thought so too, but I did not work when I tried it. Perhaps there is something else missing? To be honest I did't think about it too much. 

> The new method also looks fine, but it seems a little more verbose and therefore error-prone. Also, the decomposition is probably more stable than performing all of these operations in case you have super sheared boxes or other cases where loss of orthogonality is a possibility when you do the manual operations you have like the computation of square roots.

> Just my two cents, feel free to proceed if you think the new code is better.

I agree the decomposition method is probably more stable overall, but I find this one more straightforward to follow. Thanks for the feedback

@bdice @csadorf @klywang  thoughts on this?

**Comment by vyasr** [comment]
I'm curious, so maybe I'll have a look tomorrow, but feel free to move ahead when the maintainers are satisfied.

**Comment by vyasr** [comment]
The problem with the existing code is that when flipping a box vector for handedness it tries to reflect particles, when all it actually needs to do (because of PBCs) is just shift everything, which is automatic. At least in this case, the fix is essentially just to remove the problematic code paths altogether and flip a box vector. @lyrivera's code is doing something similar by just flipping the box vector before converting it to an upper-triangular matrix.

I've committed the code, and you can see what it looks like [here](https://github.com/glotzerlab/garnett/blob/fix/alternative_rotation_fix/garnett/trajectory.py#L1084). I think either fix is fine, but I think the bigger issue is that we need a more robust test here. While I know what the right behavior is when I see it, I had a hard time actually writing down mathematically what the problem is. If we can define exactly what invariant needs to be preserved, it would make testing this a lot easier.

**Comment by vyasr** [comment]
I actually think the old code would have broken chiral structures provided with a left-handed box, because it was trying to reflect them.

**Comment by vyasr** [comment]
In case you stick with Luis's existing fix, please reinsert the lines of code that copy the position data. Otherwise it could try and edit read-only parts of a GSD file.

**Comment by lyrivera** [comment]
> The problem with the existing code is that when flipping a box vector for handedness it tries to reflect particles, when all it actually needs to do (because of PBCs) is just shift everything, which is automatic. At least in this case, the fix is essentially just to remove the problematic code paths altogether and flip a box vector. @lyrivera's code is doing something similar by just flipping the box vector before converting it to an upper-triangular matrix.
> 
> I've committed the code, and you can see what it looks like [here](https://github.com/glotzerlab/garnett/blob/fix/alternative_rotation_fix/garnett/trajectory.py#L1084). I think either fix is fine, but I think the bigger issue is that we need a more robust test here. While I know what the right behavior is when I see it, I had a hard time actually writing down mathematically what the problem is. If we can define exactly what invariant needs to be preserved, it would make testing this a lot easier.

Thanks. That fix seems much more cleaner. I'm inclined to keep that one and discard this PR. Can you create a new PR?

**Comment by vyasr** [comment]
Sounds good, I'll make a PR on Monday.

**Comment by lyrivera** [comment]
> Sounds good, I'll make a PR on Monday.

Good. I'm closing this PR.

**Pull request closed without merging**
