### PR TITLE
Update readthedocs.yml

### PR DESCRIPTION
**Pull request by bdice**
Force ReadTheDocs to use config file v2. This is important because otherwise the config file isn't respected (usually it favors the web interface settings).

### CODE REVIEW

**Comment by bdice** [comment]
This actually fixes the problem with web interface settings that I described in #111.

**Comment by lyrivera** [comment]
This looks good. The only thing I noticed is that docstring of the `view_rotation` attribute of the `Frame` class is not being parsed into RTD.

**Comment by lyrivera** [comment]
> This looks good. The only thing I noticed is that docstring of the `view_rotation` attribute of the `Frame` class is not being parsed into RTD.

Oh, NVM. Thats one of the things I fixed in PR #106

**Review by lyrivera — APPROVED** [review]
Looks good.

**Pull request merged**
