### PR TITLE
Release/v0.6.0

### PR DESCRIPTION
**Pull request by lyrivera**
## Description

Release of v0.6.0

## How Has This Been Tested?
Current and previous tests are passing.

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/glotzerlab/garnett/blob/master/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] I have updated the documentation (if relevant).
- [x] I have added tests that cover my changes (if relevant).
- [x] All new and existing tests passed.
- [x] I have updated the [Changelog](https://github.com/glotzerlab/garnett/blob/master/changelog.rst).

### CODE REVIEW

**Comment by bdice** [comment]
Here's the criteria I'm using to review this release:

**For this PR to be approved:**
- [x] Updated changelog (Added, Fixed, Changed, Deprecated, Removed)
- [x] Updated the release version and date in the changelog
- [ ] Update the contributors _(I'll make a PR)_

**After this PR is approved:**
- [ ] Bump the version and push: `bumpversion minor  # use major, minor, or patch`
- [ ] `git push`
- [ ] Make sure docs and CI pass. Then update tags: `git push origin master --tags`
- [ ] Ask @bdice to generate and upload a tarball for [glotzerlab website](https://glotzerlab.engin.umich.edu/Downloads/garnett/). This will cause a conda-forge PR to be automatically generated by the bots.
- [ ] Verify ReadTheDocs is updated.
- [ ] Notify the lab via Slack.

**Comment by bdice** [comment]
@lyrivera This branch must be named `release/v0.6.0` instead of `Release/v0.6.0` for the CircleCI release automation to work correctly.

**Review by bdice — CHANGES_REQUESTED** [review]
See comments above and PR #130.

**Comment by lyrivera** [comment]
> @lyrivera This branch must be named `release/v0.6.0` instead of `Release/v0.6.0` for the CircleCI release automation to work correctly.

Got it.

**Comment by lyrivera** [comment]
Closing this now. Will reopen with the proper name for CCI automation.

**Pull request closed without merging**
