### PR TITLE
Build documentation on ReadTheDocs

### LINKED ISSUE #100: Host documentation on ReadTheDocs
We need to have ReadTheDocs install the package so the docs work.

Config file: https://docs.readthedocs.io/en/stable/config-file/index.html

Freud example: https://github.com/glotzerlab/freud/blob/master/.readthedocs.yml

GSD example: https://github.com/glotzerlab/gsd/blob/master/readthedocs.yml

I would recommend trying the [python method](https://docs.readthedocs.io/en/stable/config-file/v2.html#python) instead of the [conda method](https://docs.readthedocs.io/en/stable/config-file/v2.html#conda). Try creating a `requirements.txt` file in the root of the repository that specifies `numpy`, `cython`, `rowan`, and any other dependencies, then you can add that to the `.readthedocs.yml`.

### PR DESCRIPTION
**Pull request by lyrivera**
## Description
Have ReadTheDocs install the package in order for docs to work properly.

## Motivation and Context

Resolves: #100 

## How Has This Been Tested?

Testes configuration by building on ReadTheDocs

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds or improves functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation update

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/glotzerlab/garnett/blob/master/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] I have updated the documentation (if relevant).
- [ ] I have added tests that cover my changes (if relevant).
- [ ] All new and existing tests passed.
- [ ] I have updated the [Changelog](https://github.com/glotzerlab/garnett/blob/master/ChangeLog.rst).

### CODE REVIEW

**Review by bdice — APPROVED** [review]
Looks good to me - we'll need to test it on ReadTheDocs before merging, but their site seems to be down at the moment. Go into the project page and then go to the "Versions" tab and enable this branch. Try again tomorrow, maybe?

**Comment by lyrivera** [comment]
> Looks good to me - we'll need to test it on ReadTheDocs before merging, but their site seems to be down at the moment. Go into the project page and then go to the "Versions" tab and enable this branch. Try again tomorrow, maybe?

Will do, thanks

**Comment by lyrivera** [comment]
RTD is back online. Seems to work

**Comment by bdice** [comment]
@lyrivera I'm not sure that it's working. I would have expected [this page](https://garnett.readthedocs.io/en/latest/trajectory.html) to show more class documentation. Also see the log below, it appears the package was not installed.

```
Running Sphinx v1.8.5
loading translations [en]... done
making output directory...
loading intersphinx inventory from https://docs.python.org/objects.inv...
intersphinx inventory has moved: https://docs.python.org/objects.inv -> https://docs.python.org/3/objects.inv
loading intersphinx inventory from https://hoomd-blue.readthedocs.io/en/stable/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [readthedocs]: targets for 8 source files that are out of date
updating environment: 8 added, 0 changed, 0 removed
reading sources... [ 12%] credits
reading sources... [ 25%] development
reading sources... [ 37%] index
reading sources... [ 50%] installation
reading sources... [ 62%] quickstart
reading sources... [ 75%] readerswriters
reading sources... [ 87%] shapes
reading sources... [100%] trajectory

WARNING: autodoc: failed to import function 'read' from module 'garnett'; the following exception was raised:
No module named 'garnett'
WARNING: autodoc: failed to import function 'write' from module 'garnett'; the following exception was raised:
No module named 'garnett'
WARNING: autodoc: failed to import class 'reader.PosFileReader' from module 'garnett'; the following exception was raised:
No module named 'garnett'
WARNING: autodoc: failed to import class 'writer.PosFileWriter' from module 'garnett'; the following exception was raised:
No module named 'garnett'
WARNING: autodoc: failed to import class 'reader.GSDHOOMDFileReader' from module 'garnett'; the following exception was raised:
No module named 'garnett'
WARNING: autodoc: failed to import class 'writer.GSDHOOMDFileWriter' from module 'garnett'; the following exception was raised:
No module named 'garnett'
WARNING: autodoc: failed to import class 'reader.GetarFileReader' from module 'garnett'; the following exception was raised:
No module named 'garnett'
WARNING: autodoc: failed to import class 'reader.HOOMDXMLFileReader' from module 'garnett'; the following exception was raised:
No module named 'garnett'
WARNING: autodoc: failed to import class 'reader.DCDFileReader' from module 'garnett'; the following exception was raised:
No module named 'garnett'
WARNING: autodoc: failed to import class 'dcdfilereader.DCDTrajectory' from module 'garnett'; the following exception was raised:
No module named 'garnett'
WARNING: autodoc: failed to import class 'reader.PyDCDFileReader' from module 'garnett'; the following exception was raised:
No module named 'garnett'
WARNING: autodoc: failed to import class 'reader.CifFileReader' from module 'garnett'; the following exception was raised:
No module named 'garnett'
WARNING: autodoc: failed to import class 'writer.CifFileWriter' from module 'garnett'; the following exception was raised:
No module named 'garnett'
WARNING: autodoc: failed to import class 'shapes.FallbackShape' from module 'garnett'; the following exception was raised:
No module named 'garnett'
WARNING: autodoc: failed to import class 'shapes.Shape' from module 'garnett'; the following exception was raised:
No module named 'garnett'
WARNING: autodoc: failed to import class 'shapes.SphereShape' from module 'garnett'; the following exception was raised:
No module named 'garnett'
WARNING: autodoc: failed to import class 'shapes.ArrowShape' from module 'garnett'; the following exception was raised:
No module named 'garnett'
WARNING: autodoc: failed to import class 'shapes.SphereUnionShape' from module 'garnett'; the following exception was raised:
No module named 'garnett'
WARNING: autodoc: failed to import class 'shapes.PolygonShape' from module 'garnett'; the following exception was raised:
No module named 'garnett'
WARNING: autodoc: failed to import class 'shapes.SpheropolygonShape' from module 'garnett'; the following exception was raised:
No module named 'garnett'
WARNING: autodoc: failed to import class 'shapes.ConvexPolyhedronShape' from module 'garnett'; the following exception was raised:
No module named 'garnett'
WARNING: autodoc: failed to import class 'shapes.ConvexPolyhedronUnionShape' from module 'garnett'; the following exception was raised:
No module named 'garnett'
WARNING: autodoc: failed to import class 'shapes.ConvexSpheropolyhedronShape' from module 'garnett'; the following exception was raised:
No module named 'garnett'
WARNING: autodoc: failed to import class 'shapes.GeneralPolyhedronShape' from module 'garnett'; the following exception was raised:
No module named 'garnett'
WARNING: autodoc: failed to import class 'trajectory.Trajectory' from module 'garnett'; the following exception was raised:
No module named 'garnett'
WARNING: autodoc: failed to import class 'trajectory.Frame' from module 'garnett'; the following exception was raised:
No module named 'garnett'
WARNING: autodoc: failed to import class 'trajectory.Box' from module 'garnett'; the following exception was raised:
No module named 'garnett'
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [ 12%] credits
writing output... [ 25%] development
writing output... [ 37%] index
writing output... [ 50%] installation
writing output... [ 62%] quickstart
writing output... [ 75%] readerswriters
writing output... [ 87%] shapes
writing output... [100%] trajectory

generating indices... genindex
writing additional pages... search
copying static files... done
copying readthedocs static files... done
copying searchtools... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 27 warnings.
```

**Comment by lyrivera** [comment]
Hum yeah, that was my bad for rushing it without properly checking

**Pull request merged**
