### PR TITLE
Release/v0.7.0

### PR DESCRIPTION
**Pull request by bdice**
## Description
Release of garnett 0.7.0.

### CODE REVIEW

**Comment by bdice** [comment]
@glotzerlab/garnett-maintainers I'm working on the 0.7 release. There's one thing I want you to be aware about. In #152, I made it so that more "optional" dependencies were installed during the CI. This improved our ability to test the package effectively. Specifically, the CI now uses `requirements-dev.txt` instead of `requirements.txt`. However, one side effect of this is that **Cython is now installed in CI**.

**If Cython is installed,** garnett automatically tries to use it to compile the Cython `dcdreader.pyx` extension, and use that instead of the pure Python reader. The Cython DCD reader is faster, _but_ on the other hand, using Cython for this one feature prevents garnett from being a "pure Python" package.

With the releases of 0.6, garnett's CI didn't have Cython installed and instead it shipped with the "pure Python" reader and no module built from Cythonized C++. This meant that the entire package was "pure Python," which makes it _much much easier_ to deploy. If you ship a pip wheel build with the Cython extension, you will have to compile it for every platform and architecture you want to support (e.g. Linux, Mac, Windows, and also ppc64 if you support Summit). This is what we do for freud but it's a massive pain.

For now, I have changed our build process so that it does NOT use Cython when building wheels. The important consequences of this:
- DCD reading may be less efficient than possible in certain cases:
  - Installing **pip wheel** or **conda-forge** build: _slow_, uses pure Python.
  - Installing **from source** or **pip source distribution** *without* Cython installed: _slow_, uses pure Python.
  - Installing **from source** or **pip source distribution** *with* Cython installed: _fast_, uses Cython module.
- The package remains a "pure Python" package as it was deployed for 0.6.0 and 0.6.1.

**Comment by bdice** [comment]
@glotzerlab/garnett-maintainers This is ready for review. Please let me know when it's ready for merge and I'll apply the `v0.7.0` tag so it deploys. Normally this is automatic with `bumpversion` but I had to adjust a few things so I manually changed the tag.

**Comment by lyrivera** [comment]
> @glotzerlab/garnett-maintainers I'm working on the 0.7 release. There's one thing I want you to be aware about. In #152, I made it so that more "optional" dependencies were installed during the CI. This improved our ability to test the package effectively. Specifically, the CI now uses `requirements-dev.txt` instead of `requirements.txt`. However, one side effect of this is that **Cython is now installed in CI**.
> 
> **If Cython is installed,** garnett automatically tries to use it to compile the Cython `dcdreader.pyx` extension, and use that instead of the pure Python reader. The Cython DCD reader is faster, _but_ on the other hand, using Cython for this one feature prevents garnett from being a "pure Python" package.
> 
> With the releases of 0.6, garnett's CI didn't have Cython installed and instead it shipped with the "pure Python" reader and no module built from Cythonized C++. This meant that the entire package was "pure Python," which makes it _much much easier_ to deploy. If you ship a pip wheel build with the Cython extension, you will have to compile it for every platform and architecture you want to support (e.g. Linux, Mac, Windows, and also ppc64 if you support Summit). This is what we do for freud but it's a massive pain.
> 
> For now, I have changed our build process so that it does NOT use Cython when building wheels. The important consequences of this:
> 
> * DCD reading may be less efficient than possible in certain cases:
>   
>   * Installing **pip wheel** or **conda-forge** build: _slow_, uses pure Python.
>   * Installing **from source** or **pip source distribution** _without_ Cython installed: _slow_, uses pure Python.
>   * Installing **from source** or **pip source distribution** _with_ Cython installed: _fast_, uses Cython module.
> * The package remains a "pure Python" package as it was deployed for 0.6.0 and 0.6.1.

I think this is perfectly fine for the moment. IMO, avoiding such complications outweighs the performance gains since we don't have many DCD users anyways. I think it is worth adding a comment on the installation page to let users know how can they boost the performance by installing from source with Cython (basically add the bullet points summary above).

**Review by lyrivera — APPROVED** [review]
I would add a comment on the installation page letting users know can they get the faster `DCD` reader if they need it.

**Pull request merged**
